# Generated by Django 5.2.1 on 2025-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_fr',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='', max_length=100),
        ),
    ]
