# Generated by Django 5.2.1 on 2025-06-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_category_name_fr_category_name_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='phone',
        ),
    ]
