# Generated by Django 5.2.1 on 2025-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_commande_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
