# Generated by Django 5.2.1 on 2025-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commande_code_commande_phone_commande_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommande',
            name='selected_price',
            field=models.FloatField(default=0),
        ),
    ]
