# Generated by Django 5.2.1 on 2025-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemcommande_selected_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livraison',
            field=models.FloatField(default=0),
        ),
    ]
