# Generated by Django 5.2.1 on 2025-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commande_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='capture',
            field=models.ImageField(default='', upload_to='captures_commandes/'),
        ),
    ]
