# Generated by Django 5.2.1 on 2025-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_big_steak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='avec_6begat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='default_lang',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('loading', 'Loading'), ('delivered', 'Delivered')], default='waiting', max_length=20),
        ),
    ]
