# Generated by Django 5.2.1 on 2025-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_is_big_steak_commande_avec_6begat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
