# Generated by Django 5.2.1 on 2026-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_version_android', models.CharField(default='1.0.0', max_length=10)),
                ('minimum_version_ios', models.CharField(default='1.0.0', max_length=10)),
                ('force_update', models.BooleanField(default=True)),
                ('store_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.chwily.app')),
                ('appstore_url', models.URLField(default='https://apps.apple.com/mr/app/chwily/id6747934029')),
            ],
            options={
                'verbose_name': "Configuration de l'Application",
            },
        ),
    ]
