# Generated by Django 5.2.1 on 2026-09-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_appconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('base_url', models.URLField(default='https://api-jemli.oneposts.io/api/third-party/')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, help_text='Moment de livraison choisi par le client (mes_plats).', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_final_price',
            field=models.FloatField(blank=True, help_text='partner_delivery_fee + delivery_type.delivery_margin — montant payé par le client.', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='dispatch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='commande',
            name='partner_delivery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='partner_delivery_ref',
            field=models.CharField(blank=True, default='', help_text='Identifiant de la livraison renvoyé par le partenaire.', max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('looking_for_driver', 'Looking for driver'), ('driver_assigned', 'Driver assigned'), ('loading', 'Loading'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='api.deliveryprovider'),
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_margin', models.FloatField(default=50)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Envoi différé au delivery_datetime choisi par le client (mes_plats).')),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_types', to='api.deliveryprovider')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='api.deliverytype'),
        ),
        migrations.AddField(
            model_name='deliveryprovider',
            name='origin_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='api.locationpoint'),
        ),
        migrations.AddField(
            model_name='commande',
            name='location_point',
            field=models.ForeignKey(blank=True, help_text='Destination (quartier choisi par le client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='api.locationpoint'),
        ),
    ]
