# Generated by Django 5.2.1 on 2026-09-17 12:07

from django.db import migrations, models

CORRECT_BASE_URL = 'https://api-jemli.oneposts.io/api/third-party/28/08/2026/'


def fix_jemli_base_url(apps, schema_editor):
    DeliveryProvider = apps.get_model('api', 'DeliveryProvider')
    DeliveryProvider.objects.filter(code='jemli').update(base_url=CORRECT_BASE_URL)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_seed_delivery_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprovider',
            name='base_url',
            field=models.URLField(default=CORRECT_BASE_URL),
        ),
        migrations.RunPython(fix_jemli_base_url, noop),
    ]
